### ISSUE TITLE
[rfc] Stop deploying every branch?

### ISSUE THREAD

**Issue by rye** [frog-pond/ccc-server#107]
Do we _really_ need to do this? I'd rather just test that each branch builds, and run tests on the branch.

I treat deployment here like native deployment in AAO. We _never_ (read: almost never) actually test things deployed to production when we could have just built them locally.

**Comment by rye** [comment]
Okay. In its current form, then, it's useless, and so I'd say we can remove this for now.

Maybe we can revisit with something like a `deploy` label handler? (Kinda like danger, but whenever it encounters a PR that has the `deploy` label on it it deploys?)

**Comment by hawkrives** [comment]
@rye sgtm. I'll PR a removal?

**Comment by rye** [comment]
Sounds good. Go for it, it should just be deleting the relevant lines from the Circle config.

I think we could build some nice build tooling to handle this rather than shell scripting in the yaml, too, to combine this with #106. 😆
