### ISSUE TITLE
Flatten directory structure?

### ISSUE THREAD

**Issue by rye** [frog-pond/ccc-server#141]
I don't understand why we have `modules/node_modules/@frogpond`, I guess. Is there a way we can get rid of this? I.e. by moving them out to the root of the project?

That'd be appreciated.

**Comment by drewvolz** [comment]
The reasoning behind the monorepo structure https://github.com/frog-pond/ccc-server/issues/36

**Comment by rye** [comment]
Ah. That makes sense.

Something inside me really wants those to be their own repositories lol
