### ISSUE TITLE
Define user agent in one exported location

### ISSUE THREAD

**Issue by drewvolz** [frog-pond/ccc-server#34]
Right now we’re defining the user agent every time. We should export and import it from a central location.

**Comment by rye** [comment]
We should also make our user agent look cooler… 😎
```
ccc-server/1 (https://github.com/frog-pond/ccc-server)
```
just seems a bit bare.

First of all, we haven't published an API.  This project is not at v1 yet, and we should therefore change our version to match that.  (I'd be fine with `v0.1`, and just incrementing the minor version for each release.)  This change needs to be made whenever we start a release workflow.

We should load some environment information too, I think.  Specifically, we should include information about which version of node we're using, I think.  (Different node versions might have different `fetch` behavior.)

Idk.  Thoughts?

Something like
```
ccc-server/0.1.0 (docker 18.04.0; node 10.72.31728)
```
seems more appealing to me.

**Comment by hawkrives** [comment]
We're not using fetch; we're using `got`, which is a wrapper on top of node's `http` library. I don't see the appeal in saying what version of docker we're running.
