### ISSUE TITLE
Change user agent

### ISSUE THREAD

**Issue by drewvolz** [frog-pond/ccc-server#35]
The user agent should come from the ccc-server instead of the GitHub url.

**Comment by hawkrives** [comment]
just to resurface this in a better place: https://github.com/frog-pond/ccc-server/issues/34#issuecomment-386063578

**Comment by rye** [comment]
I still like this idea. `ccc-server/0.1.0 (docker 18.04.0; node 10.72.31728)` sounds like a good format to me.

**Comment by hawkrives** [comment]
Sure

**Comment by hawkrives** [comment]
We run all of our requests through https://github.com/frog-pond/ccc-server/blob/master/modules/node_modules/%40frogpond/ccc-lib/http.js, which is already setting a User-agent, so it should be as simple as editing that file.
