### ISSUE TITLE
Calendar detail contains HTML

### ISSUE THREAD

**Issue by drewvolz** [frog-pond/ccc-server#52]
1 | 2
--|--
<img width="530" alt="screen shot 2018-08-10 at 4 36 53 pm" src="https://user-images.githubusercontent.com/5240843/43987660-7b148438-9ce1-11e8-874c-7ca9b14a39b2.png"> | <img width="530" alt="screen shot 2018-08-10 at 4 36 53 pm" src="https://user-images.githubusercontent.com/5240843/43987662-839083e6-9ce1-11e8-9786-4a88ffbd727b.jpg">

**Comment by hawkrives** [comment]
Should be able to do something in

https://github.com/frog-pond/ccc-server/blob/02d940d7f1ae89f9d47ca8dbf0dbf425aad438ff/modules/node_modules/%40frogpond/ccc-lib/calendar/google.mjs#L6-L9

and do something like 

https://github.com/frog-pond/ccc-server/blob/02d940d7f1ae89f9d47ca8dbf0dbf425aad438ff/modules/node_modules/%40frogpond/ccc-lib/feeds/rss.mjs#L28
