### ISSUE TITLE
[endpoint] St. Olaf Multimedia upcoming streams

### ISSUE THREAD

**Issue by hawkrives** [frog-pond/ccc-server#59]
URL: https://www.stolaf.edu/multimedia/api/collection
Usage: https://github.com/StoDevX/AAO-React-Native/blob/47583bb99fa69c45785330591cc2276fa7a866a5/source/views/streaming/streams/list.js
Types: https://github.com/StoDevX/AAO-React-Native/blob/47583bb99fa69c45785330591cc2276fa7a866a5/source/views/streaming/streams/types.js

Suggested endpoint: `/v1/videos/stolaf`

I'm suggesting a `videos` namespace because `multimedia` or `broadcast-media` just doesn't sound right to me, and I'd like to be able to add … other things? to it. Not that I can come up with anything else, mind. I'd just like to leave the option open.

**Comment by drewvolz** [comment]
Would a `streams` endpoint sound right to you?

**Comment by hawkrives** [comment]
`v1/streams/upcoming/`, maybe? So we can add `archived` or something too?

**Comment by hawkrives** [comment]
The Carleton side has this: https://github.com/frog-pond/ccc-server/blob/bf16517b426e20ead36a8f9ac3f914ac2a4b3a77/modules/node_modules/%40frogpond/ccci-carleton-college/v1/index.mjs#L70-L72
