### ISSUE TITLE
Stop pigz-ing build cache image?

### ISSUE THREAD

**Issue by rye** [frog-pond/ccc-server#61]
The CI configuration has this currently, but this requires an installation on _every_ build.

Do we really need to use `.gz` to compress? The only thing I can think of that this gives us is reduced bandwidth consumption, but our tars seem pretty well-compressed already.

**Comment by hawkrives** [comment]
I think I tested this when we first started ccc-server and pigz-ing the image saved on build time… I don't know if that's still the case, and you may have other reasons to not compress it.

**Comment by rye** [comment]
Updated OP.

**Comment by rye** [comment]
Well, I look at it this way: if we build a 500 MiB image, that 500 MiB image has to get loaded twice. I don't expect any more than 2:1 compression with Docker images, primarily because a `docker save` `.tar` is already a `.tar` of `.tar`s.

Un-gzipping will add some additional network latency time, but will allow us to avoid installing `pigz` and reading/decompressing the image twice.  It'll also simplify the build.

I'll PR it.
